/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-tint": "#a43e00",
        "tertiary": "#006591",
        "surface-container": "#ffe9e2",
        "tertiary-container": "#00a4e9",
        "on-primary-container": "#5b1f00",
        "secondary-container": "#e2dfde",
        "primary": "#a43e00",
        "secondary-fixed": "#e5e2e1",
        "inverse-surface": "#3c2d27",
        "inverse-on-surface": "#ffede7",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#360f00",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#7d2d00",
        "surface-variant": "#f7ddd3",
        "primary-container": "#ff6d1f",
        "primary-fixed-dim": "#ffb596",
        "background": "#fff8f6",
        "surface": "#fff8f6",
        "outline": "#8d7165",
        "tertiary-fixed-dim": "#89ceff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1b1c1c",
        "primary-fixed": "#ffdbcd",
        "on-tertiary-fixed": "#001e2f",
        "error": "#ba1a1a",
        "surface-container-highest": "#f7ddd3",
        "secondary": "#5f5e5e",
        "surface-dim": "#eed5cb",
        "on-surface-variant": "#594137",
        "surface-container-high": "#fde3d9",
        "surface-container-low": "#fff1ec",
        "on-background": "#261813",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#e1bfb2",
        "on-surface": "#261813",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#004c6e",
        "error-container": "#ffdad6",
        "on-secondary-container": "#636262",
        "on-tertiary-container": "#003650",
        "surface-bright": "#fff8f6",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb596",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#c9e6ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "glass-padding": "20px",
        "container-padding-desktop": "32px",
        "container-padding-mobile": "16px"
      },
      fontFamily: {
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
